import type { Metadata } from "next";
import "./globals.css";
import { NotificationProvider } from "./components/NotificationContext";
import { Notifications } from "./components/Notifications";

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV === "development"
) {
  const { server } = await import("../../mocks/node");
  server.listen();
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NotificationProvider>
          {children}
          <Notifications />
        </NotificationProvider>
      </body>
    </html>
  );
}
